
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-4pm-4
owner: ucsb-cs156-w24
repo_name: team01-w24-4pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjg4MTU5NDI2","is_bot":false,"login":"hyi96","name":""},"headRefName":"Hao-Joke","number":21,"title":"Hao Joke Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-4/pull/21"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-HomeController","number":20,"title":"Kole home controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-4/pull/20"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-ZipCode-Controller","number":19,"title":"Kole zip code controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-4/pull/19"},{"author":{"id":"U_kgDOBXywjA","is_bot":false,"login":"ktkikuta","name":"Kole Kikuta"},"headRefName":"Kole-ZipCode","number":18,"title":"Kole zip code","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-4/pull/18"}]
